# base image
FROM python:slim-buster

RUN apt-get update
# install bcrypt dependencies
RUN apt-get install -y build-essential libffi-dev python-dev

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# set environment varibles
ENV FLASK_ENV production
ENV APP_SETTINGS project.config.ProductionConfig

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add app
COPY . /usr/src/app

# run server
CMD gunicorn -b 0.0.0.0:$PORT manage:app
